version: "3"

services:
  mysql:
    image: reubensjohn/storefront-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storefront
    ports:
      - "3306:3306/tcp"
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: 1

  storefront-app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
volumes:
  mysql-data:
